# Generated by Django 5.1.3 on 2026-01-26 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContenidoMultimedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seccion", models.CharField(max_length=20)),
                ("titulo", models.CharField(max_length=200)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EntidadConvenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_entidad", models.CharField(max_length=100)),
                (
                    "tipo_entidad",
                    models.CharField(
                        choices=[
                            ("BANCO", "Banco"),
                            ("COOPERATIVA", "Cooperativa"),
                            ("FINANCIERA", "Financiera"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("politica_credito_resumen", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("documento_identidad", models.CharField(max_length=50, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Número de Teléfono"
                    ),
                ),
                (
                    "perfil_laboral",
                    models.CharField(
                        choices=[
                            ("PENSIONADO", "Pensionado"),
                            ("DOCENTE", "Docente"),
                            ("FUERZA_PUBLICA", "Fuerza Pública"),
                            ("PUBLICO", "Empleado Público"),
                            ("PRIVADO", "Empleado Privado"),
                            ("OTRO", "Otro / Independiente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score_datacredito", models.IntegerField(default=0)),
                ("tiene_embargos", models.BooleanField(default=False)),
                ("tiene_reportes_negativos", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "agente_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatrizPerfilamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "segmento_cliente",
                    models.CharField(
                        choices=[
                            ("PENSIONADO", "Pensionado"),
                            ("DOCENTE", "Docente"),
                            ("FUERZA_PUBLICA", "Fuerza Pública"),
                            ("PUBLICO", "Empleado Público"),
                            ("PRIVADO", "Empleado Privado"),
                            ("OTRO", "Otro / Independiente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score_minimo", models.IntegerField()),
                ("antiguedad_minima_meses", models.IntegerField(default=6)),
                ("acepta_embargo", models.BooleanField(default=False)),
                ("acepta_reporte_negativo", models.BooleanField(default=False)),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_opcifin.entidadconvenio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotaSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField(verbose_name="Observación")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="web_opcifin.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Radicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_solicitado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado_proceso",
                    models.CharField(
                        choices=[
                            ("01_INGRESADO", "Lead Ingresado"),
                            ("02_DOC_PENDIENTE", "Pendiente Documentos"),
                            ("03_ESTUDIO", "En Estudio Bancario"),
                            ("04_APROBADO", "✅ Aprobado"),
                            ("05_RECHAZADO", "❌ Rechazado"),
                            ("06_DESEMBOLSADO", "💰 Desembolsado"),
                        ],
                        default="01_INGRESADO",
                        max_length=20,
                    ),
                ),
                (
                    "diagnostico_riesgo",
                    models.TextField(
                        blank=True, help_text="Notas internas del analista"
                    ),
                ),
                ("fecha_radicacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radicaciones",
                        to="web_opcifin.cliente",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web_opcifin.entidadconvenio",
                        verbose_name="Banco/Entidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchivoAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="radicaciones/%Y/%m/%d/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "radicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="web_opcifin.radicacion",
                    ),
                ),
            ],
        ),
    ]
