# Generated by Django 6.0 on 2025-12-14 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=100, unique=True)),
                ('tipo_entidad', models.CharField(choices=[('Banco', 'Banco'), ('Financiera', 'Financiera'), ('Cooperativa', 'Cooperativa')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('politica_credito_resumen', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('perfil_laboral', models.CharField(choices=[('PENSIONADO', 'Pensionado'), ('PUBLICO', 'Empleado Sector Público'), ('DOCENTE', 'Docente'), ('FFMM_POLICIA', 'FF.MM. y Policía'), ('OTRO', 'Otro')], max_length=20)),
                ('fuente_lead', models.CharField(default='Manual', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agente_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Radicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('LIBRANZA', 'Créditos por Libranza'), ('ADELANTO', 'Adelanto de Primas'), ('CARTERA', 'Negociación de Cartera en Mora'), ('HIPOTECA', 'Hipotecas'), ('REPORTE', 'Eliminación de Reportes en Centrales'), ('REFINANCIACION', 'Refinanciación')], max_length=50)),
                ('estado_proceso', models.CharField(choices=[('01_INGRESADO', '1. Lead Ingresado'), ('02_DOC_RECIBIDOS', '2. Documentación Inicial Recibida'), ('03_DIAG_RIESGO', '3. En Diagnóstico de Riesgo'), ('04_PEND_CLAVE', '4. Pendiente Clave/Acceso Entidad'), ('05_PERFILAMIENTO', '5. En Perfilamiento y Simulación'), ('06_OFERTA_PRES', '6. Oferta Viable Presentada'), ('07_PEND_AUTORIZ', '7. Pendiente Autorización de Consulta'), ('08_RADICADO', '8. Radicado Formal / En Trámite'), ('09_APROBADO', '9. Aprobado (Entidad)'), ('10_DESEMBOLSADO', '10. Desembolsado (Caso Exitoso)'), ('11_RECHAZADO', '11. Rechazado/Archivado')], default='01_INGRESADO', max_length=20)),
                ('fecha_diagnostico', models.DateTimeField(blank=True, null=True)),
                ('diagnostico_riesgo', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radicaciones', to='gestion_financiera.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='radicaciones/archivos/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('radicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='gestion_financiera.radicacion')),
            ],
        ),
        migrations.CreateModel(
            name='MatrizPerfilamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmento_cliente', models.CharField(choices=[('PENSIONADO', 'Pensionado'), ('PUBLICO', 'Empleado Sector Público'), ('DOCENTE', 'Docente'), ('FFMM_POLICIA', 'FF.MM. y Policía'), ('OTRO', 'Otro')], max_length=50)),
                ('score_minimo', models.IntegerField(default=0)),
                ('antiguedad_minima_meses', models.IntegerField(default=6)),
                ('acepta_embargo', models.BooleanField(default=False)),
                ('acepta_reporte_negativo', models.BooleanField(default=False)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='gestion_financiera.entidadconvenio')),
            ],
            options={
                'verbose_name_plural': 'Matrices de Perfilamiento',
                'unique_together': {('entidad', 'segmento_cliente')},
            },
        ),
    ]
