# Generated by Django 6.0 on 2025-12-17 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrizperfilamiento',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='matrizperfilamiento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='archivoadjunto',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fuente_lead',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='radicacion',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='score_datacredito',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tiene_embargos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tiene_reportes_negativos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.FileField(upload_to='radicaciones/archivos/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='agente_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='perfil_laboral',
            field=models.CharField(choices=[('PENSIONADO', 'Pensionado'), ('PUBLICO', 'Empleado Público'), ('PRIVADO', 'Empleado Privado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entidadconvenio',
            name='nombre_entidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entidadconvenio',
            name='politica_credito_resumen',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidadconvenio',
            name='tipo_entidad',
            field=models.CharField(choices=[('BANCO', 'Banco'), ('COOPERATIVA', 'Cooperativa'), ('FINANCIERA', 'Financiera')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matrizperfilamiento',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_financiera.entidadconvenio'),
        ),
        migrations.AlterField(
            model_name='matrizperfilamiento',
            name='score_minimo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matrizperfilamiento',
            name='segmento_cliente',
            field=models.CharField(choices=[('PENSIONADO', 'Pensionado'), ('PUBLICO', 'Empleado Público'), ('PRIVADO', 'Empleado Privado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_financiera.cliente'),
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='diagnostico_riesgo',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='estado_proceso',
            field=models.CharField(choices=[('01_INGRESADO', 'Lead Ingresado'), ('02_ESTUDIO', 'En Estudio'), ('03_APROBADO', 'Aprobado')], default='01_INGRESADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='fecha_diagnostico',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
