# Generated by Django 6.0 on 2025-12-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0002_alter_matrizperfilamiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion_financiera.cliente')),
            ],
            options={
                'verbose_name': 'Nota de Seguimiento',
                'verbose_name_plural': 'Bitácora de Notas',
            },
        ),
    ]
