# Generated by Django 6.0 on 2025-12-18 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0003_notaseguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaseguimiento',
            options={},
        ),
        migrations.RemoveField(
            model_name='radicacion',
            name='fecha_diagnostico',
        ),
        migrations.AddField(
            model_name='archivoadjunto',
            name='tipo_documento',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('LABORAL', 'Certificado Laboral'), ('PAGO', 'Desprendibles'), ('OTROS', 'Otros')], default='OTROS', max_length=20),
        ),
        migrations.AddField(
            model_name='radicacion',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_financiera.entidadconvenio', verbose_name='Banco/Entidad'),
        ),
        migrations.AddField(
            model_name='radicacion',
            name='fecha_radicacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-18'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radicacion',
            name='monto_solicitado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='archivo',
            field=models.FileField(upload_to='radicaciones/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='agente_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radicaciones', to='gestion_financiera.cliente'),
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='diagnostico_riesgo',
            field=models.TextField(blank=True, help_text='Notas internas del analista'),
        ),
        migrations.AlterField(
            model_name='radicacion',
            name='estado_proceso',
            field=models.CharField(choices=[('01_INGRESADO', 'Lead Ingresado'), ('02_DOC_PENDIENTE', 'Pendiente Documentos'), ('03_ESTUDIO', 'En Estudio Bancario'), ('04_APROBADO', '✅ Aprobado'), ('05_RECHAZADO', '❌ Rechazado'), ('06_DESEMBOLSADO', '💰 Desembolsado')], default='01_INGRESADO', max_length=20),
        ),
    ]
