# Generated by Django 6.0 on 2025-12-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0004_alter_notaseguimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('INICIO', 'Banner Principal'), ('NOSOTROS', 'Sección Nosotros'), ('VIDEO', 'Video Corporativo')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='multimedia/')),
                ('video_url', models.URLField(blank=True, help_text='Enlace de YouTube o Vimeo', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
