# Generated by Django 6.0 on 2025-12-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0005_contenidomultimedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidomultimedia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
