# Generated by Django 5.1.3 on 2026-01-26 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_financiera", "0007_cliente_email_cliente_telefono_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "servicio_interes",
                    models.CharField(
                        choices=[
                            ("Libranza", "Libranza"),
                            ("Vivienda", "Vivienda"),
                            ("Libre Inversión", "Libre Inversión"),
                            ("Personales", "Personales"),
                            ("Compra de Cartera", "Compra de Cartera"),
                            ("Reportes", "Eliminación de Reportes"),
                            ("Hipotecas", "Hipotecas"),
                            ("Retanqueos", "Retanqueos"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mensaje", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("gestionado", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="archivoadjunto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="agente_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_gestion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="documento_identidad",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="perfil_laboral",
            field=models.CharField(
                choices=[
                    ("PENSIONADO", "Pensionado"),
                    ("DOCENTE", "Docente"),
                    ("FUERZA_PUBLICA", "Fuerza Pública"),
                    ("PUBLICO", "Empleado Público"),
                    ("PRIVADO", "Empleado Privado"),
                    ("OTRO", "Otro / Independiente"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contenidomultimedia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="entidadconvenio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="matrizperfilamiento",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="matrizperfilamiento",
            name="segmento_cliente",
            field=models.CharField(
                choices=[
                    ("PENSIONADO", "Pensionado"),
                    ("DOCENTE", "Docente"),
                    ("FUERZA_PUBLICA", "Fuerza Pública"),
                    ("PUBLICO", "Empleado Público"),
                    ("PRIVADO", "Empleado Privado"),
                    ("OTRO", "Otro / Independiente"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notaseguimiento",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="radicacion",
            name="entidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion_financiera.entidadconvenio",
                verbose_name="Banco/Entidad",
            ),
        ),
        migrations.AlterField(
            model_name="radicacion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
