# Generated by Django 5.1.3 on 2026-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_financiera", "0008_lead_alter_archivoadjunto_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="mensaje",
            field=models.TextField(blank=True, null=True),
        ),
    ]
