# Generated by Django 5.1.3 on 2026-02-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_financiera", "0010_resena"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resena",
            options={"verbose_name": "Reseña", "verbose_name_plural": "Reseñas"},
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="fecha_creacion",
            new_name="fecha_registro",
        ),
        migrations.AddField(
            model_name="lead",
            name="codigo_gestion",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="estado",
            field=models.CharField(
                choices=[
                    ("NUEVO", "Nuevo - Web"),
                    ("CONTACTADO", "En Contacto"),
                    ("DOCS_RECIBIDOS", "Documentos Recibidos"),
                    ("RADICADO", "Radicado"),
                    ("APROBADO", "Aprobado"),
                    ("DESEMBOLSADO", "Desembolsado"),
                    ("RECHAZADO", "No Apto / Rechazado"),
                ],
                default="NUEVO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="fuente",
            field=models.CharField(
                default="Web Directa",
                help_text="Ej: Facebook, Instagram, Google",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="notas_asesor",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="servicio_interes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
