# Generated by Django 5.1.3 on 2026-02-17 21:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_financiera", "0012_lead_agente_asignado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="correo",
            new_name="email",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="fuente",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="mensaje",
        ),
        migrations.AddField(
            model_name="lead",
            name="cedula",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="monto_solicitado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="lead",
            name="pagaduria",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="perfil_laboral",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="agente_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_gestion_nueva",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="codigo_gestion",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="servicio_interes",
            field=models.CharField(default="General", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lead",
            name="telefono",
            field=models.CharField(default="0000000", max_length=20),
            preserve_default=False,
        ),
    ]
