# Generated by Django 5.1.3 on 2026-02-21 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_financiera",
            "0013_rename_correo_lead_email_remove_lead_fuente_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaPersonalAsesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("ultima_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerfilAsesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("Asesor", "Asesor"),
                            ("Auxiliar", "Auxiliar de Radicación"),
                            ("Coordinador", "Coordinador"),
                        ],
                        default="Asesor",
                        max_length=20,
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Inactivo", "Inactivo"),
                            ("Vacaciones", "Vacaciones"),
                        ],
                        default="Activo",
                        max_length=20,
                    ),
                ),
                (
                    "meta_mensual_unidades",
                    models.IntegerField(
                        default=10, help_text="Meta de radicaciones al mes"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recordatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateTimeField()),
                ("completado", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ContenidoMultimedia",
        ),
        migrations.RemoveField(
            model_name="notaseguimiento",
            name="cliente",
        ),
        migrations.AlterModelOptions(
            name="resena",
            options={},
        ),
        migrations.RenameField(
            model_name="radicacion",
            old_name="fecha_radicacion",
            new_name="fecha_inicio",
        ),
        migrations.RenameField(
            model_name="resena",
            old_name="fecha",
            new_name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="archivoadjunto",
            name="radicacion",
        ),
        migrations.RemoveField(
            model_name="archivoadjunto",
            name="tipo_documento",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="fecha_registro",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="gestionado",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="pagaduria",
        ),
        migrations.AddField(
            model_name="archivoadjunto",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos",
                to="gestion_financiera.lead",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="fuente_captacion",
            field=models.CharField(
                choices=[
                    ("WHATSAPP", "WhatsApp"),
                    ("FACEBOOK", "Facebook"),
                    ("TIKTOK", "TikTok"),
                    ("WEB", "Sitio Web"),
                    ("REFERIDO", "Referido"),
                    ("LLAMADA", "Llamada"),
                ],
                default="WEB",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="ultima_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="radicacion",
            name="asesor_asignado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="radicaciones_gestion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radicacion",
            name="fecha_desembolso",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="radicacion",
            name="monto_desembolsado",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="autor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resenas_cliente",
                to="gestion_financiera.cliente",
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resenas_lead",
                to="gestion_financiera.lead",
            ),
        ),
        migrations.AlterField(
            model_name="archivoadjunto",
            name="archivo",
            field=models.FileField(upload_to="adjuntos_leads/"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="agente_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="estado",
            field=models.CharField(
                choices=[
                    ("NUEVO", "Nuevo"),
                    ("CONTACTADO", "Contactado"),
                    ("DOCS_RECIBIDOS", "Documentos Recibidos"),
                    ("RADICADO", "Radicado"),
                    ("APROBADO", "Aprobado"),
                    ("DESEMBOLSADO", "Desembolsado"),
                    ("RECHAZADO", "No Apto / Rechazado"),
                ],
                default="NUEVO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="radicacion",
            name="diagnostico_riesgo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="radicacion",
            name="entidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion_financiera.entidadconvenio",
            ),
        ),
        migrations.AlterField(
            model_name="radicacion",
            name="estado_proceso",
            field=models.CharField(
                choices=[
                    ("DOCUMENTACION", "Documentación"),
                    ("RADICADO", "Radicado"),
                    ("ESTUDIO", "En Estudio"),
                    ("APROBADO", "Aprobado"),
                    ("DESEMBOLSADO", "Desembolsado"),
                    ("RECHAZADO", "Rechazado"),
                    ("DEVUELTO", "Devuelto"),
                ],
                default="DOCUMENTACION",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resena",
            name="comentario",
            field=models.TextField(default="Sin comentario"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resena",
            name="puntuacion",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="recordatorio",
            name="cliente_vinculado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion_financiera.lead",
            ),
        ),
        migrations.AddField(
            model_name="recordatorio",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordatorios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="MatrizPerfilamiento",
        ),
        migrations.DeleteModel(
            name="NotaSeguimiento",
        ),
    ]
