# Generated by Django 5.1.3 on 2026-02-25 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_financiera",
            "0014_notapersonalasesor_perfilasesor_recordatorio_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="agente_asignado",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="fuente_captacion",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="notas_asesor",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="perfil_laboral",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="servicio_interes",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="ultima_actualizacion",
        ),
        migrations.AddField(
            model_name="lead",
            name="asesor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads_asignados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="departamento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="empleador",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="lead",
            name="fuente",
            field=models.CharField(
                choices=[
                    ("WHATSAPP", "WhatsApp"),
                    ("FACEBOOK", "Facebook"),
                    ("INSTAGRAM", "Instagram"),
                    ("TIKTOK", "TikTok"),
                    ("WEB", "Sitio Web"),
                    ("REFERIDO", "Referido"),
                    ("LLAMADA", "Llamada"),
                ],
                default="PENDIENTE",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="ingreso_mensual",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="lead",
            name="nicho",
            field=models.CharField(
                choices=[
                    ("DOCENTE", "Docente"),
                    ("PENSIONADO", "Pensionado"),
                    ("SERVIDOR_PUBLICO", "Servidor Público"),
                    ("FUERZAS_ARMADAS", "Fuerzas Armadas"),
                    ("INDEPENDIENTE", "Independiente"),
                ],
                default="DESCONOCIDO",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="nombre_completo",
            field=models.CharField(default="Sin Nombre", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="notas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="prioridad",
            field=models.CharField(
                choices=[
                    ("BAJA", "Baja"),
                    ("MEDIA", "Media"),
                    ("ALTA", "Alta"),
                    ("URGENTE", "Urgente"),
                ],
                default="MEDIA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="perfilasesor",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="lead",
            name="ciudad",
            field=models.CharField(blank=True, default="VALLEDUPAR", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lead",
            name="codigo_gestion",
            field=models.CharField(
                blank=True, default="PENDIENTE", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lead",
            name="estado",
            field=models.CharField(
                choices=[
                    ("NUEVO", "Nuevo"),
                    ("CONTACTADO", "Contactado"),
                    ("EN_PROCESO", "En Proceso"),
                    ("DOCUMENTACION", "Documentación"),
                    ("RADICADO", "Radicado"),
                    ("APROBADO", "Aprobado"),
                    ("DESEMBOLSADO", "Desembolsado"),
                    ("RECHAZADO", "Rechazado"),
                ],
                default="NUEVO",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="monto_solicitado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
